[tool.poetry]
name = "greenatom"
version = "0.1.0"
description = ""
authors = ["ArtemBagin <artem.bagin@vk.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
