"""add launch table

Revision ID: 00319c33339e
Revises: 7cdad8264b40
Create Date: 2024-03-28 17:18:01.070342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00319c33339e'
down_revision: Union[str, None] = '7cdad8264b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('launch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_num', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('end_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('launch')
    # ### end Alembic commands ###
